---
- hosts: all
  become: yes 
  tasks: 
  - name: i want ping 
    ping:

  - name : i want install webserver on ubuntu node
    apt:
      name:  apache2
      state:  present

  - name : i want start webserver on ubuntu node
    apt:
      name:  apache2
      state:  started